version: '3.1'
services:
  nginx:
    restart: always
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./dist:/var/www/html/
      - /etc/nginx/cert/:/etc/nginx/cert/
      - /home/static:/home/static
